### ISSUE TITLE
API status

### ISSUE THREAD

**Issue by mf** [SalesLoft/api-example#4]
Hi,

Is there a possibility of adding a functional status endpoint not requiring oAuth tie-in? We observed several production issues this morning (timeouts, 524s etc) that did not reflect in the official https://status.salesloft.com

Having an independent (and factually accurate endpoint) would allow us to monitor API status and halt event propagation in a case of an outage, while retaining the ability to replay queued events later on

(currently using v1 version)

cheers!

**Comment by sb8244** [comment]
Hi @mf,

I apologize for the issues you encountered today and inconveniences it caused you. Of course, this is something that we strive to avoid. 

We do not have an API based status endpoint, as we use http://status.salesloft.com for all documentation of problems. Our status page will be the most up to date for any issues. In particular, metrics like throughput and error rate come automatically from our system.

If you run into these types of issues in the future but don't see a status page update, support@salesloft.com is the best route for fast communication.

Best,
Steve
